bestpractice/force-app/main/default/objects/CFG_Run_Logic__c/CFG_Run_Logic__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting will determine if Trigger,Validation rule or process builder should run or not</description>
    <label>CFG Run Logic</label>
</CustomObject>

bestpractice/force-app/main/default/objects/CFG_Run_Logic__c/fields/BypassTrigger__c.field-meta.xml
<CustomField>
    <fullName>BypassTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked triggers need to be bypassed</description>
    <label>BypassTrigger</label>
    <type>Checkbox</type>
</CustomField>

bestpractice/force-app/main/default/classes/CFG_TriggerDispatcher.cls
/**
 * @auther : Avijit
 * @purpose : this will dispatch the triggers 
 * 
 */
public with sharing class CFG_TriggerDispatcher {
    public static void run(String objectName){
        // Check for bypass flag in custom setting
        CFG_Run_Logic__c  runLogic = CFG_Run_Logic__c.getInstance();
        if(runLogic.BypassTrigger__c){
            return;
        }
        switch on objectName {
            when 'Account' {
                //handler call here
            }	
            when 'Opportunity' {		
                //handler call here
            }
            when 'CASE' {	
                //handler call here	
            }
            when 'custom__c' {
                customTriggerHandler handler = new customTriggerHandler();
                if (TRIGGER.isAfter && Trigger.isInsert){
                    handler.afterInsert(Trigger.NEW,Trigger.oldMap);
                }
            }
            when else {		  
            }
        }
        
    }
}